networks:
  web:
    name: web
  intercom:
    name: intercom

volumes:
  order_pg_vol:
  order_minio_vol:

services:
  traefik:
    image: "traefik:v3.5.2"
    security_opt:
      - no-new-privileges:true
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=web"
      - "--entryPoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      # Add Docker as a mounted volume, so that Traefik can read the labels of other services
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - web

  orderservice:
    build: .
    restart: unless-stopped
    command: [ "/app/ordersystem" ]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.orders.rule=Host(`orders.localhost`)"
      - "traefik.http.routers.orders.entrypoints=web"
      - "traefik.http.services.orders.loadbalancer.server.port=3000"
    env_file:
      - debug.env
    networks:
      - intercom
      - web

  sws:
    image: joseluisq/static-web-server:latest
    env_file:
      - debug.env
    volumes:
      - ./frontend:/public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sws.rule=Host(`localhost`)"
      - "traefik.http.routers.sws.entrypoints=web"
    networks:
      - intercom
      - web

  order-postgres:
    image: postgres:18
    volumes:
      - order_pg_vol:/var/lib/postgresql
    restart: always
    networks:
      - intercom
    ports:
      - "5555:5555"
    env_file:
      - debug.env

  order-minio:
    image: minio/minio:latest
    command: ["server", "--address", ":8500", "/data"]
    restart: unless-stopped
    env_file:
      - debug.env
    ports:
      - "8500:8500"
    volumes:
      - order_minio_vol:/data
    networks:
      - intercom